set -g default-terminal "screen-256color"
set -g escape-time 0
set -g base-index 1

setw -g mode-keys vi

set-window-option -g automatic-rename on
set-option -g set-titles on

set-option -g prefix C-a
unbind-key C-b
bind-key a send-prefix

#bind r source ~/.tmux.conf; display "~/.tmux.conf sourced!"

# panes
bind H split-window -h
bind v split-window -v

# Vim style pan selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes
bind -n M-h resize-pane -L
bind -n M-j resize-pane -D
bind -n M-k resize-pane -U
bind -n M-l resize-pane -R
