[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[colors.primary]
background = '#282828'
foreground = '#dfbf8e'

[colors.normal]
black   = '#665c54'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#e78a4e'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#dfbf8e'

[colors.bright]
black   = '#928374'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#e3a84e'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#dfbf8e'

[font]
size = 14.0

[font.bold]
family = "Ubuntu Mono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
style = "Regular"

[font.normal]
family = "Ubuntu Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[scrolling]
history = 10000
multiplier = 3

[shell]
program = "/usr/bin/bash"

[window]
decorations = "none"
dynamic_title = true
opacity = 0.9
blur = true

[window.dimensions]
columns = 100
lines = 25
